### ISSUE TITLE
跳转偏移如何实现

### ISSUE THREAD

**Issue by dspinkman** [gadzan/generatoc#1]
老师好，感谢你的分享，按指导用在了自己博客上，遇到小问题。
由于博客顶部有固定导航栏，目录跳转后顶部内容被遮挡，想请教下跳转偏移如何实现。

文科生不懂代码，还请原谅。

**Comment by gadzan** [comment]
看到你在我博客留言了，因为这个插件原本只是打算在我博客上用的，所以很多地方没有考虑周全。
你提到了很好的需求，下个更新我会加上跳转偏移的设置。
还有首次加载点击最后的heading会拉到底就是个bug，在设计的时候我也知道会出现，但是因为懒，呵呵，我也会在下个更新解决的。

**Comment by gadzan** [comment]
更新了, 增加了scrollOffset参数, 
你可以这样加上跳转偏移, 你博客的header高度应该是64px, 所以加上 scrollOffset = 64 即可.
例如: 
```javascript
const scrollOffset = 64;

const content = '.post-content'
const heading = ['h2', 'h3', 'h4', 'h5']
const selector = '#toc'
generatoc.init({ content, heading, selector, scrollOffset })
```

**Comment by dspinkman** [comment]
弄好啦~
太舒服了，感谢老师！❤
