### ISSUE TITLE
Feature / Idea - Change the URL separator from %20 to "-"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [gadzan/generatoc#14]
From:
![image](https://user-images.githubusercontent.com/16711871/145205696-3b827ed8-1933-499a-9c74-850da30d9fca.png)

To ("-"):
`hello-h3`

**Why?**
More readable URL.

**Comment by gadzan** [comment]
Good idea, I will implement it in the coming weekend.

**Comment by gadzan** [comment]
Hi ,

Please try with the scrollHistory.readableSpace set;

```javascript
scrollHistory: {
  readableSpace: true,
}
```
You can find more options  here : [https://github.com/gadzan/generatoc#other-init-options](https://github.com/gadzan/generatoc#other-init-options)

**Comment by Ezra-Siton-UIX** [comment]
Works !! Thanks :) Maybe also add this to the docs.
